language: python

## complicated way of doing a simple thing but the simple thing refused to work... :P
# I won't recommend this for learning purposes

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.55.5/hugo_0.55.5_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

before_script:
    - git checkout --orphan gh-pages

script:
    - hugo

after_success: |
    if [ -n "$GITHUB_TOKEN" ]; then
    mv docs/* .
    git rm -rf .
    rm -rf docs hugo_* 
    git add -f --ignore-errors --all
    git -c user.name='travis_ci' -c user.email='travis_ci' commit -m "ci-commit"
    git push -f -q https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG gh-pages
    fi
